// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv0YgQP6PkWbv-FJlboIhVO-SkyJrvcrk',
    appId: '1:540012225336:web:e2a3566cd84080faa217cd',
    messagingSenderId: '540012225336',
    projectId: 'test-f2495',
    authDomain: 'test-f2495.firebaseapp.com',
    storageBucket: 'test-f2495.appspot.com',
    measurementId: 'G-J5JWQY9SKH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnCj4OJc_bgTgyDo6WBO8vl1rh42QOizc',
    appId: '1:540012225336:android:f21f76c67e1492a1a217cd',
    messagingSenderId: '540012225336',
    projectId: 'test-f2495',
    storageBucket: 'test-f2495.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA-r_ciKF04bV41sAoB6P4cXhZxG7WhZ4',
    appId: '1:540012225336:ios:d51eb167a220047fa217cd',
    messagingSenderId: '540012225336',
    projectId: 'test-f2495',
    storageBucket: 'test-f2495.appspot.com',
    iosClientId: '540012225336-i7avcmquma40ku6s1urjv7m80tv282i8.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstly',
  );
}
